### ISSUE TITLE
Foreground / Background color selector issue

### ISSUE THREAD

**Issue by Rutorai** [os-js/osjs-writer-application#7]
How to reproduce the error (Master branch) :

1. Open a new Writer window
2. Click on foreground button --> nothing happen
3. Click on background button --> Color picker dialog open
4. Click in Textarea (write some text, but not required)
5. Click again on foreground button --> Now color picker dialog open :+1: 
6. Click on background button --> Now unfortunately nothing happen :-1: 

On demo app, the foreground button never open color picker.

**Comment by andersevenrud** [comment]
I believe this should take care of it: https://github.com/os-js/osjs-writer-application/pull/8

**Comment by andersevenrud** [comment]
It also seems like the background color button does not actually change its color according to the context (and defaults to white in the button, black in the dialog).

Foreground seems to work in this aspect.

**Comment by andersevenrud** [comment]
And this one should take care of that other issue: https://github.com/os-js/osjs-writer-application/pull/9

I'll merge this a bit later

**Comment by andersevenrud** [comment]
I just published a new release that should take care of this :)

**Comment by Rutorai** [comment]
Wonderfull, I will test it tomorrow ;-)
Thanks
